# Generated by Django 2.2.4 on 2023-02-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=256, unique=True)),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('description', models.TextField(db_index=True, default='')),
                ('thumbnail_url', models.URLField()),
                ('published_datetime', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
